load("@aspect_rules_js//js:defs.bzl", "js_test")

alias(
    name = "browser",
    actual = "@web_browser//:browser",
)

js_test(
    name = "runtime_test",
    copy_data_to_bin = False,
    entry_point = "@rules_web_e2e//playwright:preset_runtime_test.js",
    args = [
        "$(rootpath :browser)",
        "$(rootpath @web_browser//:manifest.json)",
    ],
    data = [
        "@rules_web_e2e//playwright:preset_runtime_test_files",
        ":browser",
        "@web_browser//:manifest.json",
    ],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)
