module(name = "browser_preset_consumer")

bazel_dep(name = "rules_web_e2e", version = "0.0.0")
local_path_override(
    module_name = "rules_web_e2e",
    path = "../..",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_python", version = "1.8.0")

browsers = use_extension("@rules_web_e2e//playwright:extensions.bzl", "browser_presets")
browsers.linux_amd64(
    name = "web_browser",
    release = "20260921",
)
use_repo(browsers, "web_browser")
