caches:
  - name: bazel
    cache_key:
      - rules-web-e2e-bazel-v1
      - agent: pipeline
      - agent: os
      - agent: arch
      - env: USE_BAZEL_VERSION
      - agent: step
        fallback_limit: true
      - env: BUILDKITE_COMMIT
    target_paths:
      - /tmp/rules-web-e2e-ci/bin
      - /tmp/rules-web-e2e-ci/bazelisk
      - /tmp/rules-web-e2e-ci/repository
      - /tmp/rules-web-e2e-ci/disk
