---
agents:
  queue: oss
steps:
- label: bazel 9.2.0 / Linux AMD64
  key: test-oss-9-2-0
  agents:
    queue: oss
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh test
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 9.2.0
- label: bazel 9.2.0 / macOS ARM64
  key: test-oss_darwin_arm64-9-2-0
  agents:
    queue: oss_darwin_arm64
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh test
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 9.2.0
- label: bazel 8.6.0 / Linux AMD64
  key: test-oss-8-6-0
  agents:
    queue: oss
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh test
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 8.6.0
- label: bazel 8.6.0 / macOS ARM64
  key: test-oss_darwin_arm64-8-6-0
  agents:
    queue: oss_darwin_arm64
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh test
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 8.6.0
- label: host browser tests (Linux AMD64)
  key: host-browser-oss-9-2-0
  agents:
    queue: oss
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh host-browser
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 9.2.0
- label: host browser tests (macOS ARM64)
  key: host-browser-oss_darwin_arm64-9-2-0
  agents:
    queue: oss_darwin_arm64
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh host-browser
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 60
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 9.2.0
- label: VRT build smoke (macOS ARM64)
  key: macos-vrt-oss_darwin_arm64-9-2-0
  agents:
    queue: oss_darwin_arm64
  command:
  - buildkite-agent cache restore --registry oss-ci-v2 --name bazel
  - bash .buildkite/run.sh macos-vrt
  - buildkite-agent cache save --registry oss-ci-v2 --name bazel
  timeout_in_minutes: 40
  artifact_paths: ".buildkite-artifacts/**/results/**/*;.buildkite-artifacts/*-results/**/*;.buildkite-artifacts/**/supervisor/**/*;.buildkite-artifacts/**/worker-build.log;.buildkite-artifacts/**/bazel-testlogs/**/test.log;bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml;examples/*/bazel-testlogs/**/test.log;examples/react/.web-e2e/logs/**/*;bcr_test/bazel-testlogs/**/test.log"
  env:
    USE_BAZEL_VERSION: 9.2.0
- label: Verify hooks
  key: verify-hooks
  command: bash .buildkite/verify-hooks.sh
  agents:
    queue: oss
  timeout_in_minutes: 15

notify:
- github_commit_status:
    context: release-ready/rules-web-e2e
    blocked_builds_as_pending: true
  if: build.branch == "main" && build.pull_request.id == null && build.tag == null
