load("@rules_python//python:defs.bzl", "py_binary", "py_test")
load(":defs.bzl", "runfiles_tools", "test_tools")

[
    test_tools(
        name = "tools" if arch == "x64" else "tools_arm64",
        target_arch = arch,
        file = "@test_tools_libmagic//:file",
        magic = "@test_tools_libmagic//:magic.mgc",
        toybox = "@test_tools_toybox//:toybox",
        visibility = ["//:__subpackages__"],
        zip = "@zip//:zip",
    )
    for arch in ["x64", "arm64"]
]

py_binary(
    name = "compile_magic",
    srcs = ["compile_magic.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "tools_test",
    size = "small",
    srcs = ["tools_test.py"],
    args = ["$(rlocationpaths :tools)"],
    data = [":tools"],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    deps = ["@rules_python//python/runfiles"],
)

[
    py_test(
        name = "elf_" + arch + "_test",
        size = "small",
        srcs = ["elf_test.py"],
        main = "elf_test.py",
        args = [str(machine), "$(rlocationpaths " + tools + ")"],
        data = [tools],
        deps = ["@rules_python//python/runfiles"],
    )
    for arch, machine, tools in [("x64", 62, ":tools"), ("arm64", 183, ":tools_arm64")]
]

config_setting(
    name = "linux_x86_64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_aarch64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
    visibility = ["//visibility:public"],
)

[
    runfiles_tools(
        name = "runfiles_tools" if arch == "x64" else "runfiles_tools_arm64",
        target_arch = arch,
        toybox = "@test_tools_toybox//:toybox",
        visibility = ["//:__subpackages__"],
    )
    for arch in ["x64", "arm64"]
]
