load("@aspect_rules_js//js:defs.bzl", "js_binary")
load(":remote.bzl", "linux_platform")

exports_files([
    "capture-launcher.sh.tpl",
    "ui-config.mjs.tpl",
    "ui-runfiles.mjs.tpl",
    "ui-launcher.mjs.tpl",
    "browser.bzl",
    "snapshots.bzl",
    "matching.bzl",
    "remote.bzl",
])

platform(
    name = "linux_amd64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    visibility = ["//visibility:public"],
)

platform(
    name = "linux_arm64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
    visibility = ["//visibility:public"],
)

linux_platform(
    name = "target_platform",
    target_compatible_with = ["@platforms//os:linux"],
)

exports_files(
    ["matching-config.ts"],
    visibility = ["//visibility:private"],
)

js_binary(
    name = "ui_wrapper_tool",
    entry_point = "ui-wrapper-tool.mjs",
    patch_node_fs = False,
    visibility = ["//visibility:private"],
)
