load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_test")
load("//tools:typescript.bzl", "tool_sources")

load("@aspect_rules_js//js:defs.bzl", "js_library")

exports_files(["linux_amd64.json"])

tool_sources(deps = ["//tools:typecheck", "//:node_modules/@bazel/runfiles"])

js_library(
    name = "supervisor",
    srcs = ["supervisor.js", "supervisor.d.ts", "package.json"],
    visibility = ["//visibility:public"],
)

js_binary(
    name = "runner",
    copy_data_to_bin = False,
    entry_point = "main.js",
    args = [
        "--worker-runfile=$(rlocationpath @actiond_linux_amd64//file)",
        "--manifest-runfile=$(rlocationpath :linux_amd64.json)",
    ],
    data = [":typecheck", "package.json", "linux_amd64.json", "@actiond_linux_amd64//file"],
    visibility = ["//visibility:public"],
)

js_test(
    name = "supervisor_test",
    size = "small",
    entry_point = "supervisor_test.js",
    data = [":typecheck", "package.json"],
    target_compatible_with = ["@platforms//os:linux", "@platforms//cpu:x86_64"],
)


js_library(
    name = "supervisor_config_test_files",
    srcs = ["supervisor_config_test.js"],
    deps = [":supervisor"],
    visibility = ["//visibility:public"],
)
