name: Release gate tests

on:
  pull_request:
    paths:
      - .github/scripts/*buildkite-release-gate.py
      - .github/workflows/module_release.yaml
      - .github/workflows/release-gate-test.yml
      - .buildkite/pipeline.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: python3 .github/scripts/test-buildkite-release-gate.py
